// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://knlujahbkgecmxppkdxz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtubHVqYWhia2dlY214cHBrZHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAzMzg4NDQsImV4cCI6MjA0NTkxNDg0NH0.lXNLcfBu-mq0U400UCEMPjE9BnCxPrBf6MHo21zAixs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);